### ISSUE TITLE
Daily commissions

### ISSUE THREAD

**Issue by lollismem** [Kronman590/genshin-primo-calculator#2]
The amount of primogems obtainable through daily commissions seems wrong, in the duration of 11 days with 1 upcoming event of 1k primogems, it says that the total of primogems obtainable is only 1385 wich doesn't make sense since 1k is from the event so only 385 through 11 days of daily commission 
![Screenshot_2024-05-03-10-49-27-892_com android chrome-edit](https://github.com/Kronman590/genshin-primo-calculator/assets/125473698/36ca39d2-7bde-48f3-b3dc-1301d8301a78)

**Comment by Kronman590** [comment]
Thank you for pointing this out, found a bug that has been persisting in the calculator this whole time giving inaccurate results.

**Comment by lollismem** [comment]
I hope you can fix it soon then :)
